name: sharding-repl-cache

services:
  # ── Config Redis ───────────────────────────────────────────
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mongo_net
  # ── Config Server ───────────────────────────────────────────
  configSrv:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: configSrv
    command: mongod --configsvr --replSet config_rs --port 27017 --dbpath /data/db
    volumes:
      - configsrv_data:/data/db
    networks:
      - mongo_net

  # ── Shard 1 (3 реплики) ─────────────────────────────────────
  shard1-1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-1
    command: mongod --shardsvr --replSet shard1_rs --port 27018 --dbpath /data/db
    volumes:
      - shard1_1_data:/data/db
    networks:
      - mongo_net

  shard1-2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-2
    command: mongod --shardsvr --replSet shard1_rs --port 27018 --dbpath /data/db
    volumes:
      - shard1_2_data:/data/db
    networks:
      - mongo_net

  shard1-3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-3
    command: mongod --shardsvr --replSet shard1_rs --port 27018 --dbpath /data/db
    volumes:
      - shard1_3_data:/data/db
    networks:
      - mongo_net

  # ── Shard 2 (3 реплики) ─────────────────────────────────────
  shard2-1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-1
    command: mongod --shardsvr --replSet shard2_rs --port 27018 --dbpath /data/db
    volumes:
      - shard2_1_data:/data/db
    networks:
      - mongo_net

  shard2-2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-2
    command: mongod --shardsvr --replSet shard2_rs --port 27018 --dbpath /data/db
    volumes:
      - shard2_2_data:/data/db
    networks:
      - mongo_net

  shard2-3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-3
    command: mongod --shardsvr --replSet shard2_rs --port 27018 --dbpath /data/db
    volumes:
      - shard2_3_data:/data/db
    networks:
      - mongo_net

  # ── Mongos Router ────────────────────────────────────────────
  mongos:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongos
    command: mongos --configdb config_rs/configSrv:27017 --port 27017 --bind_ip_all
    depends_on:
      - configSrv
      - shard1-1
      - shard1-2
      - shard1-3
      - shard2-1
      - shard2-2
      - shard2-3
    ports:
      - "27017:27017"
    networks:
      - mongo_net

  # ── Application ──────────────────────────────────────────────
  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongos
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: "mongodb://mongos:27017"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379"
    networks:
      - mongo_net

networks:
  mongo_net:
    driver: bridge

volumes:
  configsrv_data:
  shard1_1_data:
  shard1_2_data:
  shard1_3_data:
  shard2_1_data:
  shard2_2_data:
  shard2_3_data: